# Generated by Django 5.2.6 on 2025-11-15 14:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('hrac', 'Hráč'), ('trener', 'Trenér'), ('admin', 'Admin')], default='hrac', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrenerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trener_photo/', verbose_name='Fotografie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trenerprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trenér',
                'verbose_name_plural': 'Trenéři',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název týmu')),
                ('kategorie', models.CharField(blank=True, choices=[('U6-U9', 'U6-U9'), ('U10-U11', 'U10-U11'), ('U12-U13', 'U12-U13'), ('U14-U15', 'U14-U15'), ('U16-U19', 'U16-U19'), ('Muži', 'Muži'), ('Ženy', 'Ženy')], max_length=50, null=True)),
                ('stadion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Stadion')),
                ('mesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Město')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('trener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tymy', to='aplikace.trenerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Trenink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('cas', models.TimeField(verbose_name='Čas')),
                ('typ', models.CharField(choices=[('Fyzická příprava', 'Fyzická příprava'), ('Taktická připrava', 'Taktická připrava'), ('Jiný', 'Jiné')], max_length=20, verbose_name='Typ tréninku')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('stav', models.CharField(choices=[('Naplánováno', 'Naplánováno'), ('Dokončeno', 'Dokončeno')], default='Naplánováno', max_length=20, verbose_name='Stav tréninku')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treninky', to='aplikace.tym')),
            ],
            options={
                'verbose_name': 'Trénink',
                'verbose_name_plural': 'Tréninky',
                'ordering': ['-datum', '-cas'],
            },
        ),
        migrations.CreateModel(
            name='HracProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Výška (cm)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Váha (kg)')),
                ('cislo_dresu', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu')),
                ('pozice', models.CharField(blank=True, choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('CB', 'Střední obránce'), ('LB', 'Levý obránce'), ('RB', 'Pravý obránce'), ('LWB', 'Levý ofenzivní obránce'), ('RWB', 'Pravý ofenzivní obránce'), ('MF', 'Záložník'), ('CM', 'Střední záložník'), ('LM', 'Levý záložník'), ('RM', 'Pravý záložník'), ('AM', 'Ofenzivní záložník'), ('FW', 'Útočník'), ('CF', 'Střední útočník'), ('ST', 'Hrotový útočník'), ('LW', 'Levé křídlo'), ('RW', 'Pravé křídlo')], null=True, verbose_name='Pozice')),
                ('preferred_foot', models.CharField(blank=True, choices=[('Levá', 'Levá noha'), ('Pravá', 'Pravá noha')], max_length=15, null=True, verbose_name='Preferovaná noha')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hrac_photo/', verbose_name='Fotografie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hracprofile', to=settings.AUTH_USER_MODEL)),
                ('tym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hraci', to='aplikace.tym')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souper', models.CharField(max_length=100, verbose_name='Soupěř')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('cas', models.TimeField(blank=True, null=True, verbose_name='Čas')),
                ('domaci_hoste', models.CharField(choices=[('Domácí', 'Domácí'), ('Hosté', 'Hosté')], default='Domácí', max_length=10, verbose_name='Domácí/Hosté')),
                ('misto', models.CharField(blank=True, max_length=150, verbose_name='Místo')),
                ('stav', models.CharField(choices=[('Naplánováno', 'Naplánováno'), ('Dohráno', 'Dohráno')], default='Naplánováno', max_length=20, verbose_name='Stav zápasu')),
                ('vysledek_tymu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek týmu')),
                ('vysledek_soupere', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek soupeře')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapasy', to='aplikace.tym')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
                'ordering': ['datum', 'cas'],
            },
        ),
        migrations.CreateModel(
            name='DochazkaTreninky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pritomen', models.BooleanField(blank=True, default=None, null=True)),
                ('duvod', models.CharField(blank=True, max_length=250, null=True)),
                ('hlasoval_v', models.DateTimeField(auto_now=True)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.hracprofile')),
                ('trenink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.trenink')),
            ],
            options={
                'verbose_name': 'Docházka na trénink',
                'verbose_name_plural': 'Docházky na tréninky',
                'constraints': [models.UniqueConstraint(fields=('trenink', 'hrac'), name='unique_trenink_hrac')],
            },
        ),
        migrations.CreateModel(
            name='DochazkaZapasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pritomen', models.BooleanField(blank=True, null=True, verbose_name='Přítomen')),
                ('poznamka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.hracprofile')),
                ('zapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.zapas')),
            ],
            options={
                'verbose_name': 'Docházka na zápas',
                'verbose_name_plural': 'Docházky na zápasy',
                'unique_together': {('zapas', 'hrac')},
            },
        ),
    ]
