# Generated by Django 5.2.6 on 2025-10-26 08:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('hrac', 'Hráč'), ('trener', 'Trenér'), ('admin', 'Admin')], default='hrac', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrenerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo')),
                ('birth_date', models.DateField(verbose_name='Datum narození')),
                ('club', models.CharField(max_length=100, verbose_name='Klub')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trener_photo/', verbose_name='Fotografie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trenerprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trenér',
                'verbose_name_plural': 'Trenéři',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HracProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo')),
                ('birth_date', models.DateField(verbose_name='Datum narození')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Výška (cm)')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Váha (kg)')),
                ('cislo_dresu', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu')),
                ('pozice', models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('CB', 'Střední obránce'), ('LB', 'Levý obránce'), ('RB', 'Pravý obránce'), ('LWB', 'Levý ofenzivní obránce'), ('RWB', 'Pravý ofenzivní obránce'), ('MF', 'Záložník'), ('CM', 'Střední záložník'), ('LM', 'Levý záložník'), ('RM', 'Pravý záložník'), ('AM', 'Ofenzivní záložník'), ('FW', 'Útočník'), ('CF', 'Střední útočník'), ('ST', 'Hrotový útočník'), ('LW', 'Levé křídlo'), ('RW', 'Pravé křídlo')], default='ST', verbose_name='Pozice')),
                ('preferred_foot', models.CharField(choices=[('left', 'Levá noha'), ('right', 'Pravá noha'), ('both', 'Obě nohy')], default='right', max_length=15, verbose_name='Preferovaná noha')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hrac_photo/', verbose_name='Fotografie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hracprofile', to=settings.AUTH_USER_MODEL)),
                ('trener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hraci', to='aplikace.trenerprofile')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
