# Generated by Django 5.2.6 on 2025-11-16 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)], verbose_name='Minuta')),
                ('typ', models.CharField(choices=[('normalni', 'Normální'), ('penalta', 'Penalta'), ('primak', 'Přímý kop'), ('vlastni', 'Vlastní gól')], max_length=20)),
            ],
            options={
                'verbose_name': 'Gól',
                'verbose_name_plural': 'Góly',
                'ordering': ['minuta'],
            },
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('zluta', 'Žlutá'), ('cervena', 'Červená')], max_length=10)),
                ('minuta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)], verbose_name='Minuta')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Karty',
                'ordering': ['minuta'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dochazkazapasy',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='pozice',
            field=models.CharField(blank=True, choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('CB', 'Střední obránce'), ('LB', 'Levý obránce'), ('RB', 'Pravý obránce'), ('LWB', 'Levý ofenzivní obránce'), ('RWB', 'Pravý ofenzivní obránce'), ('MF', 'Záložník'), ('CM', 'Střední záložník'), ('LM', 'Levý záložník'), ('RM', 'Pravý záložník'), ('AM', 'Ofenzivní záložník'), ('FW', 'Útočník'), ('CF', 'Střední útočník'), ('ST', 'Hrotový útočník'), ('LW', 'Levé křídlo'), ('RW', 'Pravé křídlo')], max_length=5, null=True, verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='trenink',
            name='typ',
            field=models.CharField(choices=[('Fyzická příprava', 'Fyzická příprava'), ('Taktická připrava', 'Taktická příprava'), ('Jiný', 'Jiné')], max_length=20, verbose_name='Typ tréninku'),
        ),
        migrations.AddConstraint(
            model_name='dochazkazapasy',
            constraint=models.UniqueConstraint(fields=('zapas', 'hrac'), name='unique_zapas_hrac'),
        ),
        migrations.AddField(
            model_name='gol',
            name='hrac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goly', to='aplikace.hracprofile'),
        ),
        migrations.AddField(
            model_name='gol',
            name='zapas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goly', to='aplikace.zapas'),
        ),
        migrations.AddField(
            model_name='karta',
            name='hrac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karty', to='aplikace.hracprofile'),
        ),
        migrations.AddField(
            model_name='karta',
            name='zapas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karty', to='aplikace.zapas'),
        ),
    ]
