# Generated by Django 5.2.6 on 2025-10-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
