# Generated by Django 5.2.6 on 2025-10-26 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Výška (cm)'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Váha (kg)'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
    ]
