# Generated by Django 5.2.6 on 2025-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0002_gol_karta_alter_dochazkazapasy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tym',
            options={'ordering': ['nazev'], 'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='klub_photo/'),
        ),
    ]
