# Generated by Django 5.2.6 on 2025-10-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0002_alter_hracprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrac', to='aplikace.trenerprofile'),
        ),
    ]
