# Generated by Django 5.2.6 on 2025-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trenerprofile',
            name='club',
            field=models.CharField(default='Nezadán', max_length=100, verbose_name='Klub'),
        ),
    ]
