# Generated by Django 5.2.6 on 2025-11-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0003_alter_tym_options_user_first_login_alter_tym_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hracprofile',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hraci', to='aplikace.trenerprofile'),
        ),
    ]
