# Generated by Django 5.2.6 on 2025-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0003_alter_hracprofile_trener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='preferred_foot',
            field=models.CharField(choices=[('Levá', 'Levá noha'), ('Pravá', 'Pravá noha')], default='Pravá', max_length=15, verbose_name='Preferovaná noha'),
        ),
    ]
