# Generated by Django 5.2.6 on 2025-10-31 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0004_alter_hracprofile_preferred_foot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='cislo_dresu',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Levá', 'Levá noha'), ('Pravá', 'Pravá noha')], max_length=15, null=True, verbose_name='Preferovaná noha'),
        ),
    ]
