# Generated by Django 5.2.6 on 2025-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0004_hracprofile_trener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapas',
            name='vysledek_soupere',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Výsledek soupeře'),
        ),
    ]
