# Generated by Django 5.2.6 on 2025-12-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0005_alter_zapas_vysledek_soupere'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='asistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistence', to='aplikace.hracprofile', verbose_name='Asistent'),
        ),
    ]
