# Generated by Django 5.2.6 on 2025-10-17 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0005_hracprofile_cislo_dresu_hracprofile_pozice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='cislo_dresu',
            field=models.PositiveIntegerField(default='—', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='pozice',
            field=models.CharField(choices=[('GK: Brankář', 'Brankář'), ('DF: Obránce', 'Obránce'), ('CB: Střední obránce', 'Střední obránce'), ('LB: Levý obránce', 'Levý obránce'), ('RB: Pravý obránce', 'Pravý obránce'), ('LWB: Levý ofenzivní obránce', 'Levý ofenzivní obránce'), ('RWB: Pravý ofenzivní obránce', 'Pravý ofenzivní obránce'), ('MF: Záložník', 'Záložník'), ('CM: Střední záložník', 'Střední záložník'), ('LM: Levý záložník', 'Levý záložník'), ('RM: Pravý záložník', 'Pravý záložník'), ('AM: Ofenzivní záložník', 'Ofenzivní záložník'), ('FW: Útočník', 'Útočník'), ('ST: Hrotový útočník', 'Hrotový útočník'), ('LW: Levé křídlo', 'Levé křídlo'), ('RW: Pravé křídlo', 'Pravé křídlo')], default='—', verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='vek',
            field=models.PositiveIntegerField(default='—', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(99)], verbose_name='Věk'),
        ),
    ]
