# Generated by Django 5.2.6 on 2025-11-07 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0006_alter_hracprofile_pozice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trenink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('cas', models.TimeField()),
                ('misto', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('fyzicka', 'Fyzická příprava'), ('taktika', 'Taktická příprava'), ('zapas', 'Zápas'), ('jine', 'Jiné')], default='jine', max_length=20)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treninky', to='aplikace.trenerprofile')),
            ],
            options={
                'verbose_name': 'Trénink',
                'verbose_name_plural': 'Tréninky',
                'ordering': ['-datum', '-cas'],
            },
        ),
        migrations.CreateModel(
            name='DochazkaTreninky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pritomen', models.BooleanField(blank=True, default=None, null=True)),
                ('duvod', models.CharField(blank=True, max_length=250, null=True)),
                ('hlasoval_v', models.DateTimeField(auto_now=True)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.hracprofile')),
                ('trenink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.trenink')),
            ],
            options={
                'verbose_name': 'Docházka',
                'verbose_name_plural': 'Docházky',
                'constraints': [models.UniqueConstraint(fields=('trenink', 'hrac'), name='unique_trenink_hrac')],
            },
        ),
    ]
