# Generated by Django 5.2.6 on 2025-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0006_alter_hracprofile_cislo_dresu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='pozice',
            field=models.CharField(choices=[('GK: Brankář', 'Brankář'), ('DF: Obránce', 'Obránce'), ('CB: Střední obránce', 'Střední obránce'), ('LB: Levý obránce', 'Levý obránce'), ('RB: Pravý obránce', 'Pravý obránce'), ('LWB: Levý ofenzivní obránce', 'Levý ofenzivní obránce'), ('RWB: Pravý ofenzivní obránce', 'Pravý ofenzivní obránce'), ('MF: Záložník', 'Záložník'), ('CM: Střední záložník', 'Střední záložník'), ('LM: Levý záložník', 'Levý záložník'), ('RM: Pravý záložník', 'Pravý záložník'), ('AM: Ofenzivní záložník', 'Ofenzivní záložník'), ('FW: Útočník', 'Útočník'), ('CF: Střední útočník', 'Střední útočník'), ('ST: Hrotový útočník', 'Hrotový útočník'), ('LW: Levé křídlo', 'Levé křídlo'), ('RW: Pravé křídlo', 'Pravé křídlo')], default='—', verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='club',
            field=models.CharField(default='—', max_length=100, verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno'),
        ),
    ]
