# Generated by Django 5.2.6 on 2025-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0007_trenink_dochazkatreninky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trenink',
            name='misto',
        ),
        migrations.AlterField(
            model_name='trenink',
            name='cas',
            field=models.TimeField(verbose_name='Cas'),
        ),
        migrations.AlterField(
            model_name='trenink',
            name='datum',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='trenink',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='trenink',
            name='typ',
            field=models.CharField(choices=[('Fyzická příprava', 'Fyzická příprava'), ('Taktická připrava', 'Taktická příprava'), ('Jiný', 'Jiné')], max_length=20, verbose_name='Typ tréninku'),
        ),
    ]
