# Generated by Django 5.2.6 on 2025-12-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0007_remove_gol_asistent_gol_asistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='typ',
            field=models.CharField(choices=[('zluta', 'Žlutá'), ('cervena', 'Červená'), ('zluta_cervena', 'Červená ze žlutých')], max_length=17),
        ),
    ]
