# Generated by Django 5.2.6 on 2025-10-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0007_alter_hracprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='pozice',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('CB', 'Střední obránce'), ('LB', 'Levý obránce'), ('RB', 'Pravý obránce'), ('LWB', 'Levý ofenzivní obránce'), ('RWB', 'Pravý ofenzivní obránce'), ('MF', 'Záložník'), ('CM', 'Střední záložník'), ('LM', 'Levý záložník'), ('RM', 'Pravý záložník'), ('AM', 'Ofenzivní záložník'), ('FW', 'Útočník'), ('CF', 'Střední útočník'), ('ST', 'Hrotový útočník'), ('LW', 'Levé křídlo'), ('RW', 'Pravé křídlo')], default='—', verbose_name='Pozice'),
        ),
    ]
