# Generated by Django 5.2.6 on 2025-11-10 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0008_remove_trenink_misto_alter_trenink_cas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souper', models.CharField(max_length=100, verbose_name='Soupěř')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('cas', models.TimeField(blank=True, null=True, verbose_name='Čas')),
                ('misto', models.CharField(blank=True, max_length=150, verbose_name='Místo')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
                ('stav', models.CharField(choices=[('naplanovany', 'Naplánovaný'), ('dokonceny', 'Dokončený')], default='naplanovany', max_length=20, verbose_name='Stav zápasu')),
                ('vysledek_domaci', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek domácích')),
                ('vysledek_hoste', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek hostů')),
                ('dokonceno_dne', models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno dne')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapasy', to='aplikace.trenerprofile')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
                'ordering': ['datum', 'cas'],
            },
        ),
        migrations.CreateModel(
            name='DochazkaZapasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pritomen', models.BooleanField(blank=True, null=True, verbose_name='Přítomen')),
                ('poznamka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.hracprofile')),
                ('zapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='aplikace.zapas')),
            ],
            options={
                'verbose_name': 'Docházka na zápas',
                'verbose_name_plural': 'Docházky na zápasy',
                'unique_together': {('zapas', 'hrac')},
            },
        ),
    ]
