# Generated by Django 5.2.6 on 2025-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0009_zapas_dochazkazapasy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dochazkatreninky',
            options={'verbose_name': 'Docházka na trénink', 'verbose_name_plural': 'Docházky na tréninky'},
        ),
        migrations.AddField(
            model_name='zapas',
            name='club',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='stav',
            field=models.CharField(choices=[('Naplánováno', 'Naplánováno'), ('Dohráno', 'Dohráno')], default='Naplánováno', max_length=20, verbose_name='Stav zápasu'),
        ),
    ]
