# Generated by Django 5.2.6 on 2025-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0009_alter_hracprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Jméno'),
        ),
    ]
