# Generated by Django 5.2.6 on 2025-10-17 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0010_alter_hracprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='vek',
            field=models.PositiveIntegerField(default='18', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(99)], verbose_name='Věk'),
        ),
    ]
