# Generated by Django 5.2.6 on 2025-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0010_alter_dochazkatreninky_options_zapas_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='domaci_hoste',
            field=models.CharField(choices=[('Domácí', 'Domácí'), ('Hosté', 'Hosté')], default='Domácí', max_length=10, verbose_name='Domácí/Hosté'),
        ),
    ]
