# Generated by Django 5.2.6 on 2025-11-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0011_zapas_domaci_hoste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapas',
            name='vysledek_domaci',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='vysledek_hoste',
        ),
        migrations.AddField(
            model_name='zapas',
            name='vysledek_soupere',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek soupeře'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='vysledek_tymu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Výsledek týmu'),
        ),
    ]
