# Generated by Django 5.2.6 on 2025-10-17 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0011_alter_hracprofile_vek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='cislo_dresu',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu'),
        ),
    ]
