# Generated by Django 5.2.6 on 2025-10-25 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0012_alter_hracprofile_cislo_dresu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hracprofile',
            name='vek',
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Výška (cm)'),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hrac_photo/', verbose_name='Fotografie'),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='preferred_foot',
            field=models.CharField(choices=[('left', 'Levá noha'), ('right', 'Pravá noha'), ('both', 'Obě nohy')], default='right', max_length=15, verbose_name='Preferovaná noha'),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Váha (kg)'),
        ),
        migrations.AddField(
            model_name='trenerprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='trenerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.AddField(
            model_name='trenerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trener_photo/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='pozice',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('CB', 'Střední obránce'), ('LB', 'Levý obránce'), ('RB', 'Pravý obránce'), ('LWB', 'Levý ofenzivní obránce'), ('RWB', 'Pravý ofenzivní obránce'), ('MF', 'Záložník'), ('CM', 'Střední záložník'), ('LM', 'Levý záložník'), ('RM', 'Pravý záložník'), ('AM', 'Ofenzivní záložník'), ('FW', 'Útočník'), ('CF', 'Střední útočník'), ('ST', 'Hrotový útočník'), ('LW', 'Levé křídlo'), ('RW', 'Pravé křídlo')], default='ST', verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikace.trenerprofile'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='club',
            field=models.CharField(max_length=100, verbose_name='Klub'),
        ),
    ]
