# Generated by Django 5.2.6 on 2025-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0012_remove_zapas_vysledek_domaci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trenink',
            name='stav',
            field=models.CharField(choices=[('Naplánováno', 'Naplánováno'), ('Dokončeno', 'Dokončeno')], default='Naplánováno', max_length=20, verbose_name='Stav tréninku'),
        ),
    ]
