# Generated by Django 5.2.6 on 2025-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0013_trenink_stav'),
    ]

    operations = [
        migrations.AddField(
            model_name='trenerprofile',
            name='club_photo',
            field=models.ImageField(blank=True, null=True, upload_to='klub_photo/', verbose_name='Logo klubu'),
        ),
    ]
