# Generated by Django 5.2.6 on 2025-10-25 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0013_remove_hracprofile_vek_hracprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Výška (cm)'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Váha (kg)'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Telefonní číslo'),
        ),
    ]
