# Generated by Django 5.2.6 on 2025-11-10 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0014_trenerprofile_club_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
