# Generated by Django 5.2.6 on 2025-10-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0014_alter_hracprofile_height_alter_hracprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Datum narození'),
        ),
    ]
