# Generated by Django 5.2.6 on 2025-10-25 21:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0015_alter_hracprofile_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hracprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='trenerprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Trenér', 'verbose_name_plural': 'Trenéři'},
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hracprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trenerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trenerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='cislo_dresu',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrac', to='aplikace.trenerprofile'),
        ),
        migrations.AlterField(
            model_name='hracprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hracprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trenerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
