# Generated by Django 5.2.6 on 2025-11-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0015_zapas_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapas',
            name='dokonceno_dne',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='popis',
        ),
    ]
