# Generated by Django 5.2.6 on 2025-10-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0016_alter_hracprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hracprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trenerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
